---
role:
  pkg:
    # https://github.com/Tarrasch/antigen-hs

    # https://getantibody.github.io/
    # curl -sL git.io/antibody | sh -s
    - name: getantibody/tap/antibody
      os: darwin
    - name: antibody
      os: archlinux
  dir:
    - .zsh.d
  link:
    - .zshenv
    - "*.zsh:.zsh.d"
    - "functions:.zsh.d"
    - "plugins:.zsh.d"
  line:
    ".zshrc": "if [ -f ~/.zsh.d/init.zsh ]; then source ~/.zsh.d/init.zsh; fi"
  post_install:
    - command: 'echo /usr/local/bin/zsh | sudo tee -a /etc/shells; chsh -s /usr/local/bin/zsh'
      if: '! fgrep -q "/usr/local/bin/zsh" /etc/shells && [ "$CI" != true ]'
      os: darwin
    - antibody bundle < zsh_plugins.txt > ~/.zsh_plugins.sh
